### ISSUE TITLE
Loading order

### ISSUE THREAD

**Issue by heuvelc** [rik-bos/StyleSheetSwitcher#1]
Hi Rik,

Used the widget and it has great potential! I have run into an issue in the order of loading the css. The mxui.css is always loaded last but this means that any styling in your custom css may be overwritten by setting for the same class in the mxui.css

For instance: we do change the settings for footer of a modal window to be more compact to .mx-dataview-controls {padding: 6px 15px 0px;}. Using the StylesheetSwitcher this never gets applied because it is overruled by the original setting in the mxui.css

Looking at Mendix recommendation for loading custom css through the index.html page the custom.css should be loaded last.

Any reason for doing it like this? Can it be changed to always load custom styling last?

**Comment by rik-bos** [comment]
I had a project in which the mxui must be reloaded for the right custom style. I made it optional now.

Can you try the new widget file?
https://github.com/rik-bos/StyleSheetSwitcher/blob/master/test/widgets/StyleSheetSwitcher.mpk

If this does the trick for you, I will update it in the appstore.

**Comment by heuvelc** [comment]
Hi Rik,

Looks great. Let me do some more testing but it seems to work fine for me this way.

Regards

Cees

Van: Rik Bos [mailto:notifications@github.com]
Verzonden: woensdag 21 september 2016 09:00
Aan: rik-bos/StyleSheetSwitcher StyleSheetSwitcher@noreply.github.com
CC: Cees van den Heuvel cvandenheuvel@intermediad.nl; Author author@noreply.github.com
Onderwerp: Re: [rik-bos/StyleSheetSwitcher] Loading order (#1)

I had a project in which the mxui must be reloaded for the right custom style. I made it optional now.

Can you try the new widget file?
https://github.com/rik-bos/StyleSheetSwitcher/blob/master/test/widgets/StyleSheetSwitcher.mpk

If this does the trick for you, I will update it in the appstore.

**Comment by heuvelc** [comment]
HI Rik,

Works as expected, great work. Please deploy this version to the app store.

Regards

Cees van den Heuvel
+31 (0)33 303 5411
+31 (0)6 5341 8386

[Logo Intermediad mail]

Fonteinkruid 4
3931 WX  Woudenberg
www.intermediad.nlhttp://www.intermediad.nl/

Van: Rik Bos [mailto:notifications@github.com]
Verzonden: woensdag 21 september 2016 09:00
Aan: rik-bos/StyleSheetSwitcher StyleSheetSwitcher@noreply.github.com
CC: Cees van den Heuvel cvandenheuvel@intermediad.nl; Author author@noreply.github.com
Onderwerp: Re: [rik-bos/StyleSheetSwitcher] Loading order (#1)

I had a project in which the mxui must be reloaded for the right custom style. I made it optional now.

Can you try the new widget file?
https://github.com/rik-bos/StyleSheetSwitcher/blob/master/test/widgets/StyleSheetSwitcher.mpk

If this does the trick for you, I will update it in the appstore.
