### ISSUE TITLE
TypeError: logger.warning is not a function

### ISSUE THREAD

**Issue by edwinvanelk** [rik-bos/StyleSheetSwitcher#2]
We would like to use the StyleSheetSwitcher in Mendix v7.7.1

Sometimes, when refreshing a page, we get an error in the browser console:

StyleSheetSwitcherURL.js?636447162297958947:137 Uncaught (in promise) TypeError: logger.warning is not a function
    at Object.<anonymous> (StyleSheetSwitcherURL.js?636447162297958947:137)
    at mxui.js?636447162297958947:5
    at _ (mxui.js?636447162297958947:29)
    at mxui.js?636447162297958947:5
    at <anonymous>

**Comment by rik-bos** [comment]
This should be fixed in the new version (will upload it to the app store soon).

See the latest release on github for the mpk now.
