### ISSUE TITLE
Switch css style on one page

### ISSUE THREAD

**Issue by mina1585** [rik-bos/StyleSheetSwitcher#3]
I got the problem with changing style within 1 page when using the widget in Mendix 7.23
Situation:
In 1 page, once a user has style sheet A and then change to style sheet B, the widget is just adding the style sheet B without clearing out style sheet A if style A is not default. Moreover, I need to hit refresh the page to get the new style affect.
The problem continue when people change from style B to back style A, the style B is still existed so the theme will never change anymore.
If you can have a way to clean out the style that just added in last step and auto refresh the page, it would be perfect.
Thanks,

**Comment by rik-bos** [comment]
Hi Mina,

The use case of this widget is more for like a multi tenant application and due to the nature of widgets in Mx this may even be not possible.

 I'm not sure how your use case looks like. Can you describe that in more detail? Maybe I'm able to come up with a solution / work around.

If you only want to have a different style on a page, it may help to give that specific page a class.

Kind regards,
Rik

**Comment by mina1585** [comment]
Hi Rik,
The use case I'm working on is on the Mendix app, people can select & change the theme of the application and the theme will change right away on the whole app. It's similar to the situation: you change the Windows theme from light mode to dark mode and the whole screen will change right away.
Let me know if it's clear to you?
Thanks,

**Comment by rik-bos** [comment]
Hi Mina,

What I'd recommend in that case is to store the selected theme and let the user refresh the page. A possible workflow for that would be:

1. Give the page a native deeplink (eg. /p/settings)
2. Let the user select a different theme.
3. On saving of the settings object, check whether the theme has changed
4. If the theme has changed, show a popup with an HTML snippet that will trigger a refresh using the javascript code: ```document.location.reload()```.
5. The native deeplink will ensure that the user will go back to the settings page.
6. The reloaded page will use the StyleSheetSwitcher to apply the new theme.

Would that work for you?

Rik

**Comment by mina1585** [comment]
Thanks Rik. I think it would work in case the user refresh the page. It can be the solution for now.
The deeplink won't work because the theme will need to be changed on all the site and not only one page. If we do that way, we need to add the widget to all the page in the application.
Thanks.

**Comment by rik-bos** [comment]
You can try adding the widget to the layout.
